"""
Django settings for ARPortfolio project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

from decouple import config
import dj_database_url

# Cloudinary imports
import cloudinary
import cloudinary.uploader
import cloudinary.api

# =======================
# RUTAS BASE
# =======================

BASE_DIR = Path(__file__).resolve().parent.parent
CORE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# =======================
# VARIABLES DE ENTORNO
# =======================

SECRET_KEY = config("SECRET_KEY")

# Usa DEBUG desde variables de entorno (True/False)
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = ["localhost", "127.0.0.1", ".onrender.com"]

# =======================
# APPS
# =======================

INSTALLED_APPS = [
    "cloudinary_storage",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "apps.portfolio",
    "ckeditor",
    "cloudinary",
    #"django_recaptcha",
    # NO hace falta incluir whitenoise como app
]

# =======================
# MIDDLEWARE
# =======================

MIDDLEWARE = [
    "django.middleware.gzip.GZipMiddleware",
    "htmlmin.middleware.HtmlMinifyMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # inmediatamente después de SecurityMiddleware
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CKEDITOR_CONFIGS = {
    "default": {
        "allowedContent": True,
        "extraAllowedContent": "span[*]",
    }
}

EXCLUDE_FROM_MINIFYING = ("^admin/",)

GZIP_CONTENT_TYPES = [
    "text/html",
    "text/css",
    "application/json",
]

# =======================
# URLS / WSGI
# =======================

ROOT_URLCONF = "config.urls"

TEMPLATE_DIR = os.path.join(CORE_DIR, "templates")  # ROOT dir for templates

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [TEMPLATE_DIR],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# =======================
# EMAIL
# =======================

EMAILHOST_USER = config("EMAIL_HOST_USER")
EMAILHOST_PASSWD = config("EMAIL_HOST_PASSWORD")

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = EMAILHOST_USER
EMAIL_HOST_PASSWORD = EMAILHOST_PASSWD

# =======================
# DATABASE
# =======================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Si más adelante usas Postgres en Render:
# DATABASES["default"] = dj_database_url.config(
#     conn_max_age=600,
#     default=config("DATABASE_URL", default="")
# )

# =======================
# AUTH
# =======================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# =======================
# I18N
# =======================

LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Manila"
USE_I18N = True
USE_TZ = True

# =======================
# STATIC / MEDIA
# =======================


STATIC_URL = "/static/"

# Usamos la propia carpeta 'static' como raíz de estáticos
# (ya está en tu repo y contiene assets, images, js, etc.)
STATIC_ROOT = os.path.join(BASE_DIR, "static")

# No usamos STATICFILES_DIRS en este caso
STATICFILES_DIRS = []

# Storage simple de Django (sin compresión especial)
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Ficheros subidos: Cloudinary


# =======================
# RECAPTCHA
# =======================

RECAPTCHA_PUBLIC_KEY = config("RECAPTCHA_PUBLIC_KEY")
RECAPTCHA_PRIVATE_KEY = config("RECAPTCHA_PRIVATE_KEY")

# =======================
# CLOUDINARY
# =======================

CLOUDINARY_CLOUDNAME = config("CLOUD_NAME")
CLOUDINARY_APIKEY = config("CLOUD_API_KEY")
CLOUDINARY_SECRET = config("CLOUD_API_SECRET")

CLOUDINARY_STORAGE = {
    "CLOUD_NAME": CLOUDINARY_CLOUDNAME,
    "API_KEY": CLOUDINARY_APIKEY,
    "API_SECRET": CLOUDINARY_SECRET,
}

cloudinary.config(
    cloud_name=CLOUDINARY_CLOUDNAME,
    api_key=CLOUDINARY_APIKEY,
    api_secret=CLOUDINARY_SECRET,
)

# =======================
# OTROS
# =======================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

